//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsAccountingApp1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class cost
    {
        [DisplayName("Код элемента истории")]
        public int id_cost { get; set; }
        [DisplayName("Код ОС")]
        public int id_os { get; set; }
        [DisplayName("Цена")]
        public int cost1 { get; set; }
        [DisplayName("Дата изменения цены")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime costchangedate { get; set; }
    
        public virtual OS OS { get; set; }
    }
}
