//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsAccountingApp1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class osaccountingEntities : DbContext
    {
        public osaccountingEntities()
            : base("name=osaccountingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assigment> assigment { get; set; }
        public virtual DbSet<cost> cost { get; set; }
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<MOL> MOL { get; set; }
        public virtual DbSet<OS> OS { get; set; }
        public virtual DbSet<pin> pin { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<unit> unit { get; set; }
    }
}
