//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsAccountingApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pin
    {
        public int id_pin { get; set; }
        public int id_mol { get; set; }
        public int id_os { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual MOL MOL { get; set; }
        public virtual OS OS { get; set; }
    }
}
